version: '3.8'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - product_network

  product-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=mongodb
      - DB_NAME=productdb
      - DB_USERNAME=productUser
      - DB_PASSWORD=productPassword
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - product_network

volumes:
  mongodb_data:

networks:
  product_network:
    name: product_network
    driver: bridge
