spring.application.name: product-service
server:
  port: 8081
  servlet:
      context-path: /product
spring:
  data:
    mongodb:
      host: localhost
      username: productUser
      password: productPassword
      database: productdb
      authentication-database: productdb
      auto-index-creation: true